### ISSUE TITLE
Index performance problem

### ISSUE THREAD

**Issue by tomaash** [briankircho/mongoose-tree#6]
If you use "." in path, which is then processed with regex, the "." character is interpreted as "any character" and the regex is no longer left-anchored
(http://docs.mongodb.org/manual/reference/operator/regex/)
, which renders the index unusable, and queries for collections with more than 100k documents are very slow. Replacing path separator with "#" solves this problem. See my fix: https://github.com/tomaash/mongoose-tree/commit/f424f48bc4c7523074f3e5bd7036fd4a652c7974

**Comment by franck34** [comment]
:+1: 

Hope brian will wake up one day .. ;)

**Comment by franck34** [comment]
Perhaps you can pull request ?

**Comment by franck34** [comment]
brian first, and if he does not react, let's pull request on my repo if you
want

2013/6/2 Tomáš Holas notifications@github.com

**Comment by tomaash** [comment]
It's already in pull request to your repo. For now, I assume that this repository (briankircho) is no longer maintained. If there is no more activity in following months, we can register your version on mongoose-plugins as well :)

**Comment by franck34** [comment]
ok, let's do that !

2013/6/2 Tomáš Holas notifications@github.com

**Comment by franck34** [comment]
Done

https://github.com/franck34/mongoose-tree

**Comment by briankircho** [comment]
I went ahead and fixed this in the original tree plugin here, sorry it took so long

**Comment by tomaash** [comment]
Great, it's good to see this merged in.
